language: c

compiler:
        - gcc
        - clang

before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y liblua5.1-0 liblua5.1-0-dev
        - mkdir out
        - cd out
        - cmake ..

script: make
